tap 'homebrew/cask'
tap 'homebrew/core'

# dev
cask 'cocoapods'
cask 'mongodb-realm-studio'
cask 'simsim'
cask 'android-studio'
cask 'docker'
brew 'docker-compose'
brew 'python3'
cask 'miniconda'
cask 'iterm2'
cask 'visual-studio-code'
cask 'postman'
cask 'github'

# daily use
cask 'google-chrome'
cask 'spotify'
cask 'discord'
cask 'telegram'
cask 'obs'
cask 'obs-ndi'

# fresh install tools
cask 'appcleaner'
brew 'neofetch'